### ISSUE TITLE
File extensions being parsed from posted files

### ISSUE THREAD

**Issue by usenethound** [demanuel/NewsUP#19]
Uploading using your latest newsup.pl doesn't work with SABnzb due to missing file extensions on the par set which in turn doesn't allow files to be renamed or repaired in SABnzb. The yenc encoded data that's being added to usenet is missing the (dot)par2 extension. NZBGet seems to handle these files OK though
![missing extension in encode](https://cloud.githubusercontent.com/assets/14228335/9806345/77d3c86e-5811-11e5-9768-474372f0898b.png)

**Comment by demanuel** [comment]
Can you try the latest version and report back? That is a bug i fixed this week.

**Comment by usenethound** [comment]
demanuel, yes I am using the latest commit 455ce9abfd and the bug is still there

**Comment by demanuel** [comment]
Can you please test the last commit?

**Comment by usenethound** [comment]
Thanks demanuel this issue is fixed and can now be closed :)

btw the switch to Inline::C makes a HUGE difference in speed and CPU usage, cheers!

**Comment by demanuel** [comment]
Super :-)

May i ask what were the speeds you were getting, and what are the speeds you're getting now?

In terms of speed/cpu there's one more thing i want to do, but unfortunately i don't understand much about C. It will take time :-)

**Comment by usenethound** [comment]
If I recall correctly the speeds before the change to Inline::C were below or around 12MB/s. With the new changes I now get around 20MB/s but this is a limitation of posting through a VPN and in line with the speeds I get using newsmangler and gopoststuff which are the only other 2 posters worth using with a 1Gbps pipe. I'm sure I could easily hit 40-50 MB/s without the VPN in the equation

Thanks again for sharing this code with the community! It is by far the best linux usenet poster available and I look forward to future features/improvements

**Comment by demanuel** [comment]
Thanks for cool words!
