### ISSUE TITLE
Question about the article subject format

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#47]
I'm not sure how to word this but here goes. This is on a new install of Manjaro. I installed using the provided pkgbuild. Copied the newsup.conf file to ~/.config and added the information for the server, newsgroups, etc, etc. You and I had a discussion a year or so ago about the format of the header. I need it to something like this and it was working this way on my old install:

Chris_Young-The_Man_I_Want_to_Be-Flac-2009 [15/23] - "The Man I Want to Be - 04 - Gettin' You Home (The Black Dress Song).flac" (/33)

But now I am getting something like this:

 [02/23] - "Battleground - 02 - Bedroom Battleground.flac" (/30)

I don't know if there is a difference in the conf file or what the problem is. I'm not needing to use the rar or par scripts. I already have a script that does the pars. I am calling newsup from this script after the pars are created. I use this: newsup -f "$destination" -comment "$destination" to get the correct header format. It was working just fine on my old install but something has changed and I don't know what.

Now when I try to post something I'm getting this error:

Please configure all the required inputs server,port,username,password, newsgroups
Server: 
Port: 443
username: 
password: 
Newsgroups:

Here is my conf file:
[server]
server= *******
port= 443
connections= 5

[auth]
user= *****
password= ******

[metadata]
client= NewsUP

upload]
uploader= Peaveyman <News@Newsconnection.local>
newsgroups= alt.binaries.sounds.lossless.country, alt.binaries.sounds.flac, alt.binaries.sounds.lossless

[extraHeaders]
extra-header= value1
extra-header2= value2

[headerCheck]
enabled= 1
sleep= 10
server= 
port= 
user= 
password= 
retries= 3
connections = 3

[uploadit]
# Path to upload root folder
upload_root=/home/demanuel/Downloads/Linux
#Reverse name
reverse=0
#reverse filter
files_filter=.*(\.mkv|\.avi|\.mp4|\.ogv|\.flv)
#rename par
rename_par=0
#rename par arguments
rename_par_arguments=par2 c -r0
#Archive the data to upload
archive=1
#Archive arguments
archive_arguments=/usr/bin/rar a -m0 -v50M -ep -ed -r
#for 7z: 7z a -r -mx=0 -v50m
#Archive filter
archive_filter=rar$
#for 7z: \.\d{3}$
#Create SFV
create_sfv=1
#force repair
force_repair=1
#create parity archives
par=1
#Parity archive arguments
par_arguments=par2 c -r15
#Par filter
par_filter=par2$
#save nzb
save_nzb=1
#save nzb
save_nzb_path=/home/demanuel/Uploads
#upload nzb
upload_nzb=1
#force repair
force_repair=0
#temp dir
temp_dir=/data/tmp
#uploader
uploader=newsup
#args for newsup
args="-comment 'Uploaded with NewsUP'"
#ads folder
ads_folder=
#nfo file
nfo=

[irc]
# IRC server
server=irc.server.com
# IRC port
port=6667
# IRC Channel (no #)
channel=MyOwnChannel
# IRC Nick
nick=NewsUP
# IRC Nick Password
password=
# IRC Nick Password
channel_password=

 I'm sure there are things I need to change. Your help would be greatly appreciated.

**Comment by demanuel** [comment]
This was a bug.

It was parsing the -comment switch wrong. Its fixed now :-)

**Comment by peaveyman** [comment]
It still won't upload. I get the same error as before. 

Please configure all the required inputs server,port,username,password, newsgroups
Server: 
Port: 443
username: 
password: 
Newsgroups

**Comment by demanuel** [comment]
Well you need to configure those options... Can you try setting them on the command line?

Where do you have the config file? is it readable?

**Comment by peaveyman** [comment]
I have the conf file in /home/Gary/.config. I copied it from /etc/newsup and changed the ownership to my user. I have all those options set. I posted the conf file in my first post on this thread.

**Comment by demanuel** [comment]
Can you try setting them on the command line?

newsup -conn 10 -newsgroup alt.binaries.test -username asdasd -userpasswd asdasd

**Comment by peaveyman** [comment]
I have it posting using the new conf file. I think I had an extra line in it some where. But I still get this warning. It runs continuously while it's posting.  

Warning: Read after posting article: 240 Article Posted

**Comment by demanuel** [comment]
That warning is a known issue.

Please use this version for now:
https://github.com/demanuel/NewsUP/blob/8659ae2ff8188036f5fe08716e7fac10c982df1d/newsup.pl

**Comment by peaveyman** [comment]
The header check failed. Failed to connect it said. I have the server blank in the header check section of the conf file thinking it would use the server I have for uploading. Is this correct?

**Comment by demanuel** [comment]
On that version the option "newsgroups" in the config file, was named "newsgroup".

Please change the name to newsgroup and you shouldn't have any problem.

**Comment by peaveyman** [comment]
Yes that worked. Thanks.
